name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: "Features"
    labels:
      - "feat"
  - title: "Fixes"
    labels:
      - "fix"
  - title: "Maintenance"
    labels:
      - "chore"
change-template: '- $TITLE (#$NUMBER)'
no-changes-template: 'No user-facing changes in this release.'
